#//hebiao@wind-mobi.com 20180114 begin
# Makefile for the Himax touchscreen drivers.
ccflags-y += -I$(srctree)/drivers/misc/wind_driver/wind_device_info/
obj-$(CONFIG_TOUCHSCREEN_HX852xES)   	+= himax_platform.o himax_ic.o himax_common.o himax_debug.o
obj-$(CONFIG_TOUCHSCREEN_HIMAX_ITO_TEST)   	+= 	himax_ito_test.o
#//hebiao@wind-mobi.com 20180114 end

